[package]
name = "drive-todo"
description = "Google Drive synced TODO-list application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
